# Copyright (c) 2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

apiVersion: v1
kind: Pod
metadata:
  name: engine
  labels:
    app: "correlator"
spec:
  containers:
    - name: correlator
      image: correlator-image
      ports:
        - containerPort: 15903
---
apiVersion: v1
kind: Service
metadata:
  name: correlator
spec:
  selector:
    app: correlator
  ports:
  - protocol: TCP
    port: 15903
    targetPort: 15903
---
apiVersion: v1
kind: Pod
metadata:
  name: iaf
spec:
  containers:
    - name: iaf
      image: iaf-image
      ports:
        - containerPort: 16903
