# Copyright (c) 2015-2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

version: '2'
services:
    # Runs the Apama correlator with the Weather sample, using an Ant-exported project
    correlator:
        # build the image for this container from the Dockerfile in this directory
        build: .
        # Connect this container to the 'front' network created below
        networks:
            - front

    # Runs the Apama dashboard server, which connects to the correlator container to query and visualise the state of our sample. This
    # container exposes the standard dashboard server port to the host, so that you can run the Apama dashboard viewer against <HOST>:3278 in
    # order to access the dashboard.
    dashboardserver:
        image: apama
        # Exposes the dashboard data and management ports to the same ports on the host operating system. You may wish to change the port that
        # they are exposed to on the host; the host port is on the left, the container port is on the right.
        ports:
            - 3278:3278 
            - 28888:28888
        # Connect this container to the 'front' network created below
        networks:
            - front
        command: "dashboard_server -c default:correlator:15903:false"

networks:
    front:
