# Copyright (c) 2015-2016 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

version: '3.3'
services:
    qry-correlators:
        image: ${QUERIES_IMAGE}
        deploy:
           replicas: 2
        ports: 
          -  target: 15903 
             mode: host
        networks:
          - qry-network
networks:
    qry-network:
       external: 
         name: ${EXTERNAL_NETWORK_PREFIX}_qry-network

