# Copyright (c) 2017,2018 Software AG, Darmstadt, Germany and/or its licensors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this 
# file except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. 
# See the License for the specific language governing permissions and limitations under the License.
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool
spec:
  template:
    metadata:
      name: cluster-tool
    spec:
      containers:
      - name: cluster-tool-0
        image: 'clustertool-image'
        args: ["-t", "2000", "configure", "-n", "main", "-s", "qry-tcdb-svc:9410"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: LICENSE_URL
          value: 'http://www.terracotta.org/retriever.php?n=TerracottaDB101linux.xml'
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
   name: qry-tcdb-svc
spec:
  selector:
     app: qry-tcdb
  ports:
    - protocol: TCP
      port: 9410
      targetPort: 9410
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: qry-tcdb
spec:
  serviceName: "qry-tcdb-svc"
  replicas: 1
  selector:
    matchLabels:
      app: qry-tcdb
  template:
    metadata:
      labels:
        app: qry-tcdb
    spec:
      containers:
        - name: qry-tcdb
          image: 'tc-image'
          env: 
          - name: ACCEPT_EULA
            value: 'Y'
          - name: OFFHEAP_RESOURCE1_NAME
            value: 'main'
          - name: OFFHEAP_RESOURCE1_UNIT
            value: 'MB'
          - name: OFFHEAP_RESOURCE1_SIZE
            value: '512'
          ports:
            - containerPort: 9410
