# Create an image from the base Apama image, with the MemoryStore application in it ready to deploy
from store/softwareag/apama-correlator:10.1
COPY init.yaml MemoryStoreCounter.mon /apama_work/MemoryStore/
