# Copyright (c) 2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

version: '3.3'
services:
    # Runs the Apama correlator, connecting to UM in the 'um' container, which may be on the same or a separate host.
    # This correlator receives event from channel 'UM_TestChannel'
    apamareceiver:
        image: ${CORR_IMAGE}
        # Connect this container to the 'receiver' network created below
        networks:
            - receiver
        depends_on:
            - umsample-umhost
        # Start up the correlator, init-receiver.yaml lists EPL files for this correlator
        command: correlator --config /apama_work/UMSample/um-connectivity.yaml --config /apama_work/UMSample/init-receiver.yaml


    # Runs the Apama correlator, connecting to UM in the 'um' container, which may be on the same or a separate host.
    # This correlator sends event to the channel 'UM_TestChannel'
    apamasender:
        image: ${CORR_IMAGE}
        # Connect this container to the 'sender' network created below
        networks:
            - sender
        depends_on:
            - umsample-umhost
        # Start up the correlator, init-sender.yaml lists EPL files for this correlator
        command: correlator --config /apama_work/UMSample/um-connectivity.yaml --config /apama_work/UMSample/init-sender.yaml

networks:
    sender:
       external: 
         name: ${EXTERNAL_NETWORK_PREFIX}_sender
    receiver:
       external: 
         name: ${EXTERNAL_NETWORK_PREFIX}_receiver
 
