# Copyright (c) 2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

apiVersion: v1
kind: Pod
metadata:
  name: bus
  labels:
    app: "um"
spec:
  containers:
    - name: um
      image: um-image
      ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: umhost
spec:
  selector:
    app: um
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Pod
metadata:
  name: sender
spec:
  containers:
    - name: sender
      image: correlator-image
      ports:
        - containerPort: 15903
      command: ["correlator", "--config", "/apama_work/UMSample/um-connectivity.yaml", "--config", "/apama_work/UMSample/init-sender.yaml"]
---
apiVersion: v1
kind: Pod
metadata:
  name: receiver
spec:
  containers:
    - name: receiver
      image: correlator-image
      ports:
        - containerPort: 15903
      command: ["correlator", "--config", "/apama_work/UMSample/um-connectivity.yaml", "--config", "/apama_work/UMSample/init-receiver.yaml"]

