# Copyright (c) 2017-2018 Software AG, Darmstadt, Germany and/or its licensors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this 
# file except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. 
# See the License for the specific language governing permissions and limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: umsample-sender
spec:
  initContainers:
    - name: wait-for-um
      image: busybox
      command: ['sh', '-c', 'until nslookup umsample-umhost; do echo waiting for UM; sleep 2; done;']
  containers:
    - name: umsample-sender
      image: correlator-image
      ports:
        - containerPort: 15903
      command: ["correlator", "--config", "/apama_work/UMSample/um-connectivity.yaml", "--config", "/apama_work/UMSample/init-sender.yaml"]
---
apiVersion: v1
kind: Pod
metadata:
  name: umsample-receiver
spec:
  initContainers:
    - name: wait-for-um
      image: busybox
      command: ['sh', '-c', 'until nslookup umsample-umhost; do echo waiting for UM; sleep 2; done;']
  containers:
    - name: umsample-receiver
      image: correlator-image
      ports:
        - containerPort: 15903
      command: ["correlator", "--config", "/apama_work/UMSample/um-connectivity.yaml", "--config", "/apama_work/UMSample/init-receiver.yaml"]

