# Copyright (c) 2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

apiVersion: v1
kind: Pod
metadata:
  name: simple-sample
spec:
  containers:
    - name: simple-sample
      image: simple-image
      ports:
        - containerPort: 15903
