# Create an image from the base Apama image, with an IAF (File adapter) configuration in it
from store/softwareag/apama-correlator:10.1
COPY File.xml inputFile.txt File-static.xml /apama_work/Adapter/
