# Copyright (c) 2015-2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

version: '2'
services:
    # Runs the Apama correlator with the MemoryStore-based application
    correlator:
        # Build the image for this container from the Dockerfile in the current directory, which puts EPL files on top of a base Apama image.
        build: .
        # Take the /apama_work/MemoryStoreData/ volume, and make it our working directory so the correlator's MemoryStore plugin stores its data here
        volumes:
            - data:/apama_work/MemoryStoreData/

# Create the data volume
volumes:
    data:
