# Copyright (c) 2017 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG

apiVersion: v1
kind: Pod
metadata:
  name: memstore-sample
spec:
  containers:
    - name: memstore-sample
      image: memstore-image
      ports:
        - containerPort: 15903
      volumeMounts:
        - mountPath: /apama_work/MemoryStoreData
          name: memorystore-data
  volumes:
    - name: memorystore-data
      emptyDir: {}
