# Create an image from the base Apama image, copying the project in it ready to deploy
from store/softwareag/apama-correlator:10.1
COPY init.yaml /apama_work/Weather/
COPY monitors /apama_work/Weather/monitors
COPY bundle_instance_files /apama_work/Weather/bundle_instance_files
