from store/softwareag/apama-correlator:10.1

MAINTAINER SoftwareAG

# Copy the UM libraries required for Apama's native integration with UM.
COPY ./cplus/lib/x86_64/ /um_libs/

# Append /um_libs to LD_LIBRARY_PATH so that UM shared libraries can be
# dynamically loaded by Apama Correlator at runtime
ENV LD_LIBRARY_PATH=/um_libs/:$LD_LIBRARY_PATH
