version: '2'
services:
    # Runs the Apama correlator with an application that talks to the IAF and issues commands to the File adapter
    correlator:
        # Build the image for this container from the Dockerfile in ./deployment/, which puts the EPL for this application on top of a base
        # Apama image
        build: ./deployment/
        working_dir: /apama_work/Adapter/
        command: correlator --config init.yaml

    # Starts the IAF running the File adapter, which connects to the contained correlator. The IAF configuration is built into the image, using
    # a Dockerfile that builds on top of the base Apama image.
    iaf:
        # Build the image for this container from the Dockerfile in ./iaf/, which puts IAF configuration on top of a base Apama image
        build: ./iaf/
        working_dir: /apama_work/Adapter/
        command: iaf File.xml
        depends_on:
            - correlator
